[[constraint]]
  name = "github.com/aymerick/raymond"
  version = "2.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/matrix-org/gomatrix"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"
